package com.neuedu.mapper;

import com.neuedu.entity.ApplyInspect;
import com.neuedu.entity.ApplyInspectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApplyInspectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_inspect
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    long countByExample(ApplyInspectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_inspect
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int deleteByExample(ApplyInspectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_inspect
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int deleteByPrimaryKey(Integer applyInspectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_inspect
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int insert(ApplyInspect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_inspect
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int insertSelective(ApplyInspect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_inspect
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    List<ApplyInspect> selectByExample(ApplyInspectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_inspect
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    ApplyInspect selectByPrimaryKey(Integer applyInspectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_inspect
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int updateByExampleSelective(@Param("record") ApplyInspect record, @Param("example") ApplyInspectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_inspect
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int updateByExample(@Param("record") ApplyInspect record, @Param("example") ApplyInspectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_inspect
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int updateByPrimaryKeySelective(ApplyInspect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_inspect
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int updateByPrimaryKey(ApplyInspect record);
}