package com.neuedu.mapper;

import com.neuedu.entity.Constants;
import com.neuedu.entity.ConstantsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConstantsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_constants
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    long countByExample(ConstantsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_constants
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int deleteByExample(ConstantsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_constants
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int deleteByPrimaryKey(Integer consId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_constants
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int insert(Constants record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_constants
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int insertSelective(Constants record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_constants
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    List<Constants> selectByExample(ConstantsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_constants
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    Constants selectByPrimaryKey(Integer consId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_constants
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int updateByExampleSelective(@Param("record") Constants record, @Param("example") ConstantsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_constants
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int updateByExample(@Param("record") Constants record, @Param("example") ConstantsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_constants
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int updateByPrimaryKeySelective(Constants record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_constants
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int updateByPrimaryKey(Constants record);
}