package com.neuedu.mapper;

import com.neuedu.entity.ConstantsType;
import com.neuedu.entity.ConstantsTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConstantsTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_constants_type
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    long countByExample(ConstantsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_constants_type
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int deleteByExample(ConstantsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_constants_type
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int deleteByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_constants_type
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int insert(ConstantsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_constants_type
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int insertSelective(ConstantsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_constants_type
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    List<ConstantsType> selectByExample(ConstantsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_constants_type
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    ConstantsType selectByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_constants_type
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int updateByExampleSelective(@Param("record") ConstantsType record, @Param("example") ConstantsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_constants_type
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int updateByExample(@Param("record") ConstantsType record, @Param("example") ConstantsTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_constants_type
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int updateByPrimaryKeySelective(ConstantsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_constants_type
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int updateByPrimaryKey(ConstantsType record);
}