package com.neuedu.mapper;

import com.neuedu.entity.InspectItem;
import com.neuedu.entity.InspectItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InspectItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspect_item
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    long countByExample(InspectItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspect_item
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int deleteByExample(InspectItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspect_item
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int deleteByPrimaryKey(Integer inspectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspect_item
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int insert(InspectItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspect_item
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int insertSelective(InspectItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspect_item
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    List<InspectItem> selectByExample(InspectItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspect_item
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    InspectItem selectByPrimaryKey(Integer inspectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspect_item
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int updateByExampleSelective(@Param("record") InspectItem record, @Param("example") InspectItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspect_item
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int updateByExample(@Param("record") InspectItem record, @Param("example") InspectItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspect_item
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int updateByPrimaryKeySelective(InspectItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_inspect_item
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    int updateByPrimaryKey(InspectItem record);
}