package com.neuedu.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ApplyInspectExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_apply_inspect
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_apply_inspect
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_apply_inspect
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_inspect
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public ApplyInspectExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_inspect
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_inspect
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_inspect
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_inspect
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_inspect
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_inspect
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_inspect
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_inspect
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_inspect
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_inspect
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_apply_inspect
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andApplyInspectIdIsNull() {
            addCriterion("apply_inspect_id is null");
            return (Criteria) this;
        }

        public Criteria andApplyInspectIdIsNotNull() {
            addCriterion("apply_inspect_id is not null");
            return (Criteria) this;
        }

        public Criteria andApplyInspectIdEqualTo(Integer value) {
            addCriterion("apply_inspect_id =", value, "applyInspectId");
            return (Criteria) this;
        }

        public Criteria andApplyInspectIdNotEqualTo(Integer value) {
            addCriterion("apply_inspect_id <>", value, "applyInspectId");
            return (Criteria) this;
        }

        public Criteria andApplyInspectIdGreaterThan(Integer value) {
            addCriterion("apply_inspect_id >", value, "applyInspectId");
            return (Criteria) this;
        }

        public Criteria andApplyInspectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("apply_inspect_id >=", value, "applyInspectId");
            return (Criteria) this;
        }

        public Criteria andApplyInspectIdLessThan(Integer value) {
            addCriterion("apply_inspect_id <", value, "applyInspectId");
            return (Criteria) this;
        }

        public Criteria andApplyInspectIdLessThanOrEqualTo(Integer value) {
            addCriterion("apply_inspect_id <=", value, "applyInspectId");
            return (Criteria) this;
        }

        public Criteria andApplyInspectIdIn(List<Integer> values) {
            addCriterion("apply_inspect_id in", values, "applyInspectId");
            return (Criteria) this;
        }

        public Criteria andApplyInspectIdNotIn(List<Integer> values) {
            addCriterion("apply_inspect_id not in", values, "applyInspectId");
            return (Criteria) this;
        }

        public Criteria andApplyInspectIdBetween(Integer value1, Integer value2) {
            addCriterion("apply_inspect_id between", value1, value2, "applyInspectId");
            return (Criteria) this;
        }

        public Criteria andApplyInspectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("apply_inspect_id not between", value1, value2, "applyInspectId");
            return (Criteria) this;
        }

        public Criteria andMedicalIdIsNull() {
            addCriterion("medical_id is null");
            return (Criteria) this;
        }

        public Criteria andMedicalIdIsNotNull() {
            addCriterion("medical_id is not null");
            return (Criteria) this;
        }

        public Criteria andMedicalIdEqualTo(Integer value) {
            addCriterion("medical_id =", value, "medicalId");
            return (Criteria) this;
        }

        public Criteria andMedicalIdNotEqualTo(Integer value) {
            addCriterion("medical_id <>", value, "medicalId");
            return (Criteria) this;
        }

        public Criteria andMedicalIdGreaterThan(Integer value) {
            addCriterion("medical_id >", value, "medicalId");
            return (Criteria) this;
        }

        public Criteria andMedicalIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("medical_id >=", value, "medicalId");
            return (Criteria) this;
        }

        public Criteria andMedicalIdLessThan(Integer value) {
            addCriterion("medical_id <", value, "medicalId");
            return (Criteria) this;
        }

        public Criteria andMedicalIdLessThanOrEqualTo(Integer value) {
            addCriterion("medical_id <=", value, "medicalId");
            return (Criteria) this;
        }

        public Criteria andMedicalIdIn(List<Integer> values) {
            addCriterion("medical_id in", values, "medicalId");
            return (Criteria) this;
        }

        public Criteria andMedicalIdNotIn(List<Integer> values) {
            addCriterion("medical_id not in", values, "medicalId");
            return (Criteria) this;
        }

        public Criteria andMedicalIdBetween(Integer value1, Integer value2) {
            addCriterion("medical_id between", value1, value2, "medicalId");
            return (Criteria) this;
        }

        public Criteria andMedicalIdNotBetween(Integer value1, Integer value2) {
            addCriterion("medical_id not between", value1, value2, "medicalId");
            return (Criteria) this;
        }

        public Criteria andInspectIdIsNull() {
            addCriterion("inspect_id is null");
            return (Criteria) this;
        }

        public Criteria andInspectIdIsNotNull() {
            addCriterion("inspect_id is not null");
            return (Criteria) this;
        }

        public Criteria andInspectIdEqualTo(Integer value) {
            addCriterion("inspect_id =", value, "inspectId");
            return (Criteria) this;
        }

        public Criteria andInspectIdNotEqualTo(Integer value) {
            addCriterion("inspect_id <>", value, "inspectId");
            return (Criteria) this;
        }

        public Criteria andInspectIdGreaterThan(Integer value) {
            addCriterion("inspect_id >", value, "inspectId");
            return (Criteria) this;
        }

        public Criteria andInspectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("inspect_id >=", value, "inspectId");
            return (Criteria) this;
        }

        public Criteria andInspectIdLessThan(Integer value) {
            addCriterion("inspect_id <", value, "inspectId");
            return (Criteria) this;
        }

        public Criteria andInspectIdLessThanOrEqualTo(Integer value) {
            addCriterion("inspect_id <=", value, "inspectId");
            return (Criteria) this;
        }

        public Criteria andInspectIdIn(List<Integer> values) {
            addCriterion("inspect_id in", values, "inspectId");
            return (Criteria) this;
        }

        public Criteria andInspectIdNotIn(List<Integer> values) {
            addCriterion("inspect_id not in", values, "inspectId");
            return (Criteria) this;
        }

        public Criteria andInspectIdBetween(Integer value1, Integer value2) {
            addCriterion("inspect_id between", value1, value2, "inspectId");
            return (Criteria) this;
        }

        public Criteria andInspectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("inspect_id not between", value1, value2, "inspectId");
            return (Criteria) this;
        }

        public Criteria andInspectNameIsNull() {
            addCriterion("inspect_name is null");
            return (Criteria) this;
        }

        public Criteria andInspectNameIsNotNull() {
            addCriterion("inspect_name is not null");
            return (Criteria) this;
        }

        public Criteria andInspectNameEqualTo(String value) {
            addCriterion("inspect_name =", value, "inspectName");
            return (Criteria) this;
        }

        public Criteria andInspectNameNotEqualTo(String value) {
            addCriterion("inspect_name <>", value, "inspectName");
            return (Criteria) this;
        }

        public Criteria andInspectNameGreaterThan(String value) {
            addCriterion("inspect_name >", value, "inspectName");
            return (Criteria) this;
        }

        public Criteria andInspectNameGreaterThanOrEqualTo(String value) {
            addCriterion("inspect_name >=", value, "inspectName");
            return (Criteria) this;
        }

        public Criteria andInspectNameLessThan(String value) {
            addCriterion("inspect_name <", value, "inspectName");
            return (Criteria) this;
        }

        public Criteria andInspectNameLessThanOrEqualTo(String value) {
            addCriterion("inspect_name <=", value, "inspectName");
            return (Criteria) this;
        }

        public Criteria andInspectNameLike(String value) {
            addCriterion("inspect_name like", value, "inspectName");
            return (Criteria) this;
        }

        public Criteria andInspectNameNotLike(String value) {
            addCriterion("inspect_name not like", value, "inspectName");
            return (Criteria) this;
        }

        public Criteria andInspectNameIn(List<String> values) {
            addCriterion("inspect_name in", values, "inspectName");
            return (Criteria) this;
        }

        public Criteria andInspectNameNotIn(List<String> values) {
            addCriterion("inspect_name not in", values, "inspectName");
            return (Criteria) this;
        }

        public Criteria andInspectNameBetween(String value1, String value2) {
            addCriterion("inspect_name between", value1, value2, "inspectName");
            return (Criteria) this;
        }

        public Criteria andInspectNameNotBetween(String value1, String value2) {
            addCriterion("inspect_name not between", value1, value2, "inspectName");
            return (Criteria) this;
        }

        public Criteria andFeeIsNull() {
            addCriterion("fee is null");
            return (Criteria) this;
        }

        public Criteria andFeeIsNotNull() {
            addCriterion("fee is not null");
            return (Criteria) this;
        }

        public Criteria andFeeEqualTo(BigDecimal value) {
            addCriterion("fee =", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeNotEqualTo(BigDecimal value) {
            addCriterion("fee <>", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeGreaterThan(BigDecimal value) {
            addCriterion("fee >", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("fee >=", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeLessThan(BigDecimal value) {
            addCriterion("fee <", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("fee <=", value, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeIn(List<BigDecimal> values) {
            addCriterion("fee in", values, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeNotIn(List<BigDecimal> values) {
            addCriterion("fee not in", values, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fee between", value1, value2, "fee");
            return (Criteria) this;
        }

        public Criteria andFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fee not between", value1, value2, "fee");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNull() {
            addCriterion("is_del is null");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNotNull() {
            addCriterion("is_del is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelEqualTo(String value) {
            addCriterion("is_del =", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotEqualTo(String value) {
            addCriterion("is_del <>", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThan(String value) {
            addCriterion("is_del >", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThanOrEqualTo(String value) {
            addCriterion("is_del >=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThan(String value) {
            addCriterion("is_del <", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThanOrEqualTo(String value) {
            addCriterion("is_del <=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLike(String value) {
            addCriterion("is_del like", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotLike(String value) {
            addCriterion("is_del not like", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelIn(List<String> values) {
            addCriterion("is_del in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotIn(List<String> values) {
            addCriterion("is_del not in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelBetween(String value1, String value2) {
            addCriterion("is_del between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotBetween(String value1, String value2) {
            addCriterion("is_del not between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_apply_inspect
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 21 09:05:41 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_apply_inspect
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}