package com.neuedu.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class ApplyChecking implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_checking.apply_check_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private Integer applyCheckId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_checking.medical_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private Integer medicalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_checking.check_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private Integer checkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_checking.check_name
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private String checkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_checking.fee
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private BigDecimal fee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_checking.status
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_checking.is_del
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private String isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_checking.create_time
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_apply_checking
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_checking.apply_check_id
     *
     * @return the value of t_apply_checking.apply_check_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public Integer getApplyCheckId() {
        return applyCheckId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_checking.apply_check_id
     *
     * @param applyCheckId the value for t_apply_checking.apply_check_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setApplyCheckId(Integer applyCheckId) {
        this.applyCheckId = applyCheckId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_checking.medical_id
     *
     * @return the value of t_apply_checking.medical_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public Integer getMedicalId() {
        return medicalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_checking.medical_id
     *
     * @param medicalId the value for t_apply_checking.medical_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setMedicalId(Integer medicalId) {
        this.medicalId = medicalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_checking.check_id
     *
     * @return the value of t_apply_checking.check_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public Integer getCheckId() {
        return checkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_checking.check_id
     *
     * @param checkId the value for t_apply_checking.check_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setCheckId(Integer checkId) {
        this.checkId = checkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_checking.check_name
     *
     * @return the value of t_apply_checking.check_name
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public String getCheckName() {
        return checkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_checking.check_name
     *
     * @param checkName the value for t_apply_checking.check_name
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setCheckName(String checkName) {
        this.checkName = checkName == null ? null : checkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_checking.fee
     *
     * @return the value of t_apply_checking.fee
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_checking.fee
     *
     * @param fee the value for t_apply_checking.fee
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_checking.status
     *
     * @return the value of t_apply_checking.status
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_checking.status
     *
     * @param status the value for t_apply_checking.status
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_checking.is_del
     *
     * @return the value of t_apply_checking.is_del
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_checking.is_del
     *
     * @param isDel the value for t_apply_checking.is_del
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel == null ? null : isDel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_checking.create_time
     *
     * @return the value of t_apply_checking.create_time
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_checking.create_time
     *
     * @param createTime the value for t_apply_checking.create_time
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_apply_checking
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", applyCheckId=").append(applyCheckId);
        sb.append(", medicalId=").append(medicalId);
        sb.append(", checkId=").append(checkId);
        sb.append(", checkName=").append(checkName);
        sb.append(", fee=").append(fee);
        sb.append(", status=").append(status);
        sb.append(", isDel=").append(isDel);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}