package com.neuedu.entity;

import java.io.Serializable;

public class ConstantsType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_constants_type.type_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_constants_type.code
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_constants_type.name
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_constants_type
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_constants_type.type_id
     *
     * @return the value of t_constants_type.type_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_constants_type.type_id
     *
     * @param typeId the value for t_constants_type.type_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_constants_type.code
     *
     * @return the value of t_constants_type.code
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_constants_type.code
     *
     * @param code the value for t_constants_type.code
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_constants_type.name
     *
     * @return the value of t_constants_type.name
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_constants_type.name
     *
     * @param name the value for t_constants_type.name
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_constants_type
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", typeId=").append(typeId);
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}