package com.neuedu.entity;

import java.io.Serializable;

public class Constants implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_constants.cons_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private Integer consId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_constants.cons_type
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private String consType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_constants.cons_code
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private String consCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_constants.cons_name
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private String consName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_constants
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_constants.cons_id
     *
     * @return the value of t_constants.cons_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public Integer getConsId() {
        return consId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_constants.cons_id
     *
     * @param consId the value for t_constants.cons_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setConsId(Integer consId) {
        this.consId = consId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_constants.cons_type
     *
     * @return the value of t_constants.cons_type
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public String getConsType() {
        return consType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_constants.cons_type
     *
     * @param consType the value for t_constants.cons_type
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setConsType(String consType) {
        this.consType = consType == null ? null : consType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_constants.cons_code
     *
     * @return the value of t_constants.cons_code
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public String getConsCode() {
        return consCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_constants.cons_code
     *
     * @param consCode the value for t_constants.cons_code
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setConsCode(String consCode) {
        this.consCode = consCode == null ? null : consCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_constants.cons_name
     *
     * @return the value of t_constants.cons_name
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public String getConsName() {
        return consName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_constants.cons_name
     *
     * @param consName the value for t_constants.cons_name
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setConsName(String consName) {
        this.consName = consName == null ? null : consName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_constants
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", consId=").append(consId);
        sb.append(", consType=").append(consType);
        sb.append(", consCode=").append(consCode);
        sb.append(", consName=").append(consName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}