package com.neuedu.entity;

import java.io.Serializable;
import java.util.Date;

public class Dept implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.dept_code
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private Integer deptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.dept_name
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.dept_leader
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private String deptLeader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.parent_code
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private Integer parentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.dept_type
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private String deptType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.is_del
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private String isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.create_time
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_dept
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.dept_code
     *
     * @return the value of t_dept.dept_code
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public Integer getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.dept_code
     *
     * @param deptCode the value for t_dept.dept_code
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setDeptCode(Integer deptCode) {
        this.deptCode = deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.dept_name
     *
     * @return the value of t_dept.dept_name
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.dept_name
     *
     * @param deptName the value for t_dept.dept_name
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.dept_leader
     *
     * @return the value of t_dept.dept_leader
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public String getDeptLeader() {
        return deptLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.dept_leader
     *
     * @param deptLeader the value for t_dept.dept_leader
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setDeptLeader(String deptLeader) {
        this.deptLeader = deptLeader == null ? null : deptLeader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.parent_code
     *
     * @return the value of t_dept.parent_code
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public Integer getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.parent_code
     *
     * @param parentCode the value for t_dept.parent_code
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setParentCode(Integer parentCode) {
        this.parentCode = parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.dept_type
     *
     * @return the value of t_dept.dept_type
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public String getDeptType() {
        return deptType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.dept_type
     *
     * @param deptType the value for t_dept.dept_type
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setDeptType(String deptType) {
        this.deptType = deptType == null ? null : deptType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.is_del
     *
     * @return the value of t_dept.is_del
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.is_del
     *
     * @param isDel the value for t_dept.is_del
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel == null ? null : isDel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.create_time
     *
     * @return the value of t_dept.create_time
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.create_time
     *
     * @param createTime the value for t_dept.create_time
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dept
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", deptCode=").append(deptCode);
        sb.append(", deptName=").append(deptName);
        sb.append(", deptLeader=").append(deptLeader);
        sb.append(", parentCode=").append(parentCode);
        sb.append(", deptType=").append(deptType);
        sb.append(", isDel=").append(isDel);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}