package com.neuedu.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class DoctorLevel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_doctor_level.level_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private Integer levelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_doctor_level.level_name
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private String levelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_doctor_level.cost
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private BigDecimal cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_doctor_level
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_level.level_id
     *
     * @return the value of t_doctor_level.level_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public Integer getLevelId() {
        return levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_level.level_id
     *
     * @param levelId the value for t_doctor_level.level_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_level.level_name
     *
     * @return the value of t_doctor_level.level_name
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public String getLevelName() {
        return levelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_level.level_name
     *
     * @param levelName the value for t_doctor_level.level_name
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setLevelName(String levelName) {
        this.levelName = levelName == null ? null : levelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor_level.cost
     *
     * @return the value of t_doctor_level.cost
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public BigDecimal getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor_level.cost
     *
     * @param cost the value for t_doctor_level.cost
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_doctor_level
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", levelId=").append(levelId);
        sb.append(", levelName=").append(levelName);
        sb.append(", cost=").append(cost);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}