package com.neuedu.entity;

import java.io.Serializable;

public class Doctor implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_doctor.doc_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private Integer docId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_doctor.doc_name
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private String docName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_doctor.gender
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_doctor.dept_code
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private Integer deptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_doctor.level_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private Integer levelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_doctor
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor.doc_id
     *
     * @return the value of t_doctor.doc_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public Integer getDocId() {
        return docId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor.doc_id
     *
     * @param docId the value for t_doctor.doc_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setDocId(Integer docId) {
        this.docId = docId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor.doc_name
     *
     * @return the value of t_doctor.doc_name
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public String getDocName() {
        return docName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor.doc_name
     *
     * @param docName the value for t_doctor.doc_name
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setDocName(String docName) {
        this.docName = docName == null ? null : docName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor.gender
     *
     * @return the value of t_doctor.gender
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor.gender
     *
     * @param gender the value for t_doctor.gender
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor.dept_code
     *
     * @return the value of t_doctor.dept_code
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public Integer getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor.dept_code
     *
     * @param deptCode the value for t_doctor.dept_code
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setDeptCode(Integer deptCode) {
        this.deptCode = deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_doctor.level_id
     *
     * @return the value of t_doctor.level_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public Integer getLevelId() {
        return levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_doctor.level_id
     *
     * @param levelId the value for t_doctor.level_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_doctor
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", docId=").append(docId);
        sb.append(", docName=").append(docName);
        sb.append(", gender=").append(gender);
        sb.append(", deptCode=").append(deptCode);
        sb.append(", levelId=").append(levelId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}