package com.neuedu.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class MedicalRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.medical_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private Integer medicalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.name
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.gender
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.age
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.birthday
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.id_card
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.address
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.dept_code
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private Integer deptCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.doc_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private Integer docId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.level_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private Integer levelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.visiting_time
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private Date visitingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.is_book
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private String isBook;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.amount
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.status
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.is_del
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private String isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.create_time
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_medical_record
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.medical_id
     *
     * @return the value of t_medical_record.medical_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public Integer getMedicalId() {
        return medicalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.medical_id
     *
     * @param medicalId the value for t_medical_record.medical_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setMedicalId(Integer medicalId) {
        this.medicalId = medicalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.name
     *
     * @return the value of t_medical_record.name
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.name
     *
     * @param name the value for t_medical_record.name
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.gender
     *
     * @return the value of t_medical_record.gender
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.gender
     *
     * @param gender the value for t_medical_record.gender
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.age
     *
     * @return the value of t_medical_record.age
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.age
     *
     * @param age the value for t_medical_record.age
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.birthday
     *
     * @return the value of t_medical_record.birthday
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.birthday
     *
     * @param birthday the value for t_medical_record.birthday
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.id_card
     *
     * @return the value of t_medical_record.id_card
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.id_card
     *
     * @param idCard the value for t_medical_record.id_card
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.address
     *
     * @return the value of t_medical_record.address
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.address
     *
     * @param address the value for t_medical_record.address
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.dept_code
     *
     * @return the value of t_medical_record.dept_code
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public Integer getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.dept_code
     *
     * @param deptCode the value for t_medical_record.dept_code
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setDeptCode(Integer deptCode) {
        this.deptCode = deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.doc_id
     *
     * @return the value of t_medical_record.doc_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public Integer getDocId() {
        return docId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.doc_id
     *
     * @param docId the value for t_medical_record.doc_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setDocId(Integer docId) {
        this.docId = docId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.level_id
     *
     * @return the value of t_medical_record.level_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public Integer getLevelId() {
        return levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.level_id
     *
     * @param levelId the value for t_medical_record.level_id
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.visiting_time
     *
     * @return the value of t_medical_record.visiting_time
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public Date getVisitingTime() {
        return visitingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.visiting_time
     *
     * @param visitingTime the value for t_medical_record.visiting_time
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setVisitingTime(Date visitingTime) {
        this.visitingTime = visitingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.is_book
     *
     * @return the value of t_medical_record.is_book
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public String getIsBook() {
        return isBook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.is_book
     *
     * @param isBook the value for t_medical_record.is_book
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setIsBook(String isBook) {
        this.isBook = isBook == null ? null : isBook.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.amount
     *
     * @return the value of t_medical_record.amount
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.amount
     *
     * @param amount the value for t_medical_record.amount
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.status
     *
     * @return the value of t_medical_record.status
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.status
     *
     * @param status the value for t_medical_record.status
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.is_del
     *
     * @return the value of t_medical_record.is_del
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.is_del
     *
     * @param isDel the value for t_medical_record.is_del
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel == null ? null : isDel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.create_time
     *
     * @return the value of t_medical_record.create_time
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.create_time
     *
     * @param createTime the value for t_medical_record.create_time
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medical_record
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", medicalId=").append(medicalId);
        sb.append(", name=").append(name);
        sb.append(", gender=").append(gender);
        sb.append(", age=").append(age);
        sb.append(", birthday=").append(birthday);
        sb.append(", idCard=").append(idCard);
        sb.append(", address=").append(address);
        sb.append(", deptCode=").append(deptCode);
        sb.append(", docId=").append(docId);
        sb.append(", levelId=").append(levelId);
        sb.append(", visitingTime=").append(visitingTime);
        sb.append(", isBook=").append(isBook);
        sb.append(", amount=").append(amount);
        sb.append(", status=").append(status);
        sb.append(", isDel=").append(isDel);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}