package com.neuedu.entity;

import java.io.Serializable;

public class MedicalRecordWithBLOBs extends MedicalRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.complaint
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private String complaint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.cm_hisotry
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private String cmHisotry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.cm_cure
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private String cmCure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.past_history
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private String pastHistory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_medical_record.allergy
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private String allergy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_medical_record
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.complaint
     *
     * @return the value of t_medical_record.complaint
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public String getComplaint() {
        return complaint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.complaint
     *
     * @param complaint the value for t_medical_record.complaint
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setComplaint(String complaint) {
        this.complaint = complaint == null ? null : complaint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.cm_hisotry
     *
     * @return the value of t_medical_record.cm_hisotry
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public String getCmHisotry() {
        return cmHisotry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.cm_hisotry
     *
     * @param cmHisotry the value for t_medical_record.cm_hisotry
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setCmHisotry(String cmHisotry) {
        this.cmHisotry = cmHisotry == null ? null : cmHisotry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.cm_cure
     *
     * @return the value of t_medical_record.cm_cure
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public String getCmCure() {
        return cmCure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.cm_cure
     *
     * @param cmCure the value for t_medical_record.cm_cure
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setCmCure(String cmCure) {
        this.cmCure = cmCure == null ? null : cmCure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.past_history
     *
     * @return the value of t_medical_record.past_history
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public String getPastHistory() {
        return pastHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.past_history
     *
     * @param pastHistory the value for t_medical_record.past_history
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setPastHistory(String pastHistory) {
        this.pastHistory = pastHistory == null ? null : pastHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_medical_record.allergy
     *
     * @return the value of t_medical_record.allergy
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public String getAllergy() {
        return allergy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_medical_record.allergy
     *
     * @param allergy the value for t_medical_record.allergy
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    public void setAllergy(String allergy) {
        this.allergy = allergy == null ? null : allergy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_medical_record
     *
     * @mbg.generated Tue Apr 21 09:05:41 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", complaint=").append(complaint);
        sb.append(", cmHisotry=").append(cmHisotry);
        sb.append(", cmCure=").append(cmCure);
        sb.append(", pastHistory=").append(pastHistory);
        sb.append(", allergy=").append(allergy);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}